default['couchbase']['repository']['yum']['centos6']['i386'] = "http://packages.couchbase.com/rpm/couchbase-centos62-i686.repo"
default['couchbase']['repository']['yum']['centos6']['x86_64'] = "http://packages.couchbase.com/rpm/couchbase-centos62-x86_64.repo"
default['couchbase']['repository']['yum']['centos5']['i386'] = "http://packages.couchbase.com/rpm/couchbase-centos55-i386.repo"
default['couchbase']['repository']['yum']['centos5']['x86_64'] = "http://packages.couchbase.com/rpm/couchbase-centos55-x86_64.repo"
default['couchbase']['repository']['apt']['ubuntu']['12.04'] = "http://packages.couchbase.com/ubuntu/couchbase-ubuntu1204.list"
default['couchbase']['repository']['apt']['ubuntu']['11.10'] = "http://packages.couchbase.com/ubuntu/couchbase-ubuntu1110.list"
default['couchbase']['repository']['apt']['ubuntu']['10.04'] = "http://packages.couchbase.com/ubuntu/couchbase-ubuntu1004.list"
